AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Backlog Git Webhook → Bitrise Build Trigger (AWS Lambda)

Resources:
  BacklogWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: backlog-git-webhook-to-bitrise
      Runtime: nodejs24.x
      Handler: index.handler
      CodeUri: .
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          SECRET: CHANGE_ME
      Events:
        WebhookApi:
          Type: HttpApi
          Properties:
            Path: /backlog-git-webhook-to-bitrise/{secret}/{proxy+}
            Method: POST